version: "3.9"

services:

  mysql-db:
    image: mysql:8.0
    container_name: mysql-bibliotheque
    restart: always
    environment:
      MYSQL_DATABASE: gestion_bibliotheque
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  app:
    image: gestion-bibliotheque:1.0
    container_name: springboot-bibliotheque
    depends_on:
      - mysql-db
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/gestion_bibliotheque?useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_JPA_HIBERNATE_DDL_AUTO: update

volumes:
  mysql-data:
