name: CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1 Récupérer le code (Dockerfile, compose, scripts)
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2 Télécharger l’artefact généré par la CI
      - name: Download JAR artifact from CI
        uses: actions/download-artifact@v4
        with:
          name: application-jar
          path: target/

      # 3 Login Docker Hub
      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

      # 4 Build image Docker à partir du JAR (déjà testé)
      - name: Build Docker image
        run: docker build -t ayetayadi01/gestion-bibliotheque:1.0 .

      # 5 Push image Docker Hub
      - name: Push Docker image
        run: docker push ayetayadi01/gestion-bibliotheque:1.0

      # 6 Déploiement sur la VM Azure
      - name: Deploy on Azure VM
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_SSH_KEY }}
          script: |
            cd /opt/gestion-bibliotheque
            ./deploy.sh
